### ISSUE TITLE
AWX_ADMIN_USER/PASSWORD defined at deploy will persists through restarts

### ISSUE THREAD

**Issue by geoffritter** [ikke-t/awx_pod#11]
The admin user/password defined at deploy time persists through restarts, this might be an unintended security concern for some users.

**Comment by ikke-t** [comment]
I don't now have an active test setup, but does it use it from env any more if you change it from the GUI? I'd suspect it's stored into DB after that. So it's probably enough to add  text into README that it's only setup password, and if used for anything else than development, one should change it from GUI.

**Comment by geoffritter** [comment]
The user recreates it self with whatever is set in the
/etc/containers/pod/awx.yaml file and restarting the pod. I was able to
stop this by commenting out both instances of the user/pass parameters.
