### ISSUE TITLE
Strange line

### ISSUE THREAD

**Issue by alqu** [ikke-t/awx_pod#12]
Where does this line belong to? I guess to the upper line, no?
https://github.com/ikke-t/awx_pod/blob/9a08614ef6ce6ec9b35c8c28d6d584f367344bca/tasks/main.yml#L116

**Comment by ikke-t** [comment]
It belongs to the block: https://github.com/ikke-t/awx_pod/blob/9a08614ef6ce6ec9b35c8c28d6d584f367344bca/tasks/main.yml#L27

**Comment by alqu** [comment]
Ah, sorry! Didn't see it... 🙈
