### ISSUE TITLE
Switch to sclorg postgres containers

### ISSUE THREAD

**Issue by Klaas-** [ikke-t/awx_pod#5]
Hi,
I'm thinking about using your ansible role for running an awx container for longer usage, so I am thinking about upgradeablity. The docker library containers do not support upgrading between versions, so I am thinking about changing this role to use the sclorg container. They support upgrades.
https://github.com/sclorg/postgresql-container/blob/generated/10/root/usr/share/container-scripts/postgresql/README.md#upgrading-database-by-switching-to-newer-postgresql-image-version

If you'd consider accepting a change this big I'll create a PR for it.

Greetings
Klaas

**Comment by ikke-t** [comment]
Sounds like a good improvement, please go ahead!

**Comment by ikke-t** [comment]
hmmm, shouldn't this issue be resolved already?

**Comment by Klaas-** [comment]
This was solved via https://github.com/ikke-t/awx_pod/pull/7
